---
- name: install common dependencies
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
  with_items:
    - git
    - build-essential
    - libtool
    - libssl-dev
    - autoconf
    - automake
    - unzip
  when: ansible_os_family == "Debian"

- name: install add-apt-repostory
  sudo: yes
  apt: name=software-properties-common state=latest

- name: add oracle java repository
  sudo: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: accept java 8 license
  sudo: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: install oracle java 8
  sudo: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
