---
- name: download sources
  get_url:
    url: "{{ dynomitedb_download_url }}"
    dest: /usr/local/src/dynomitedb-{{ dynomitedb_version }}.zip

- name: extract dynomitedb archive
  unarchive:
    src: /usr/local/src/dynomitedb-{{ dynomitedb_version }}.zip
    dest: /usr/local/src
    creates: /usr/local/src/dynomite-{{ dynomitedb_version }}/Makefile.am
    copy: no

- name: autoreconf dynomitedb
  command: autoreconf -fvi
  args:
    chdir: /usr/local/src/dynomite-{{ dynomitedb_version }}
    creates: /usr/local/src/dynomite-{{ dynomitedb_version }}/configure

- name: configure dynomitedb
  command: ./configure --enable-debug=log
  args:
    chdir: /usr/local/src/dynomite-{{ dynomitedb_version }}
    creates: /usr/local/src/dynomite-{{ dynomitedb_version }}/Makefile

- name: compile dynomitedb
  command: make
  args:
    chdir: /usr/local/src/dynomite-{{ dynomitedb_version }}
    creates: /usr/local/src/dynomite-{{ dynomitedb_version }}/src/dynomite
